### ISSUE TITLE
Wrong org

### ISSUE THREAD

**Issue by tsaleh** [pivotal-golang/envoy#1]
I think https://github.com/pivotal-golang is for pivotal projects that are go-specific, but project-agnostic.  Can we move this to either https://github.com/pivotal-cf-experimental or https://github.com/cloudfoundry-incubator, since it's specific to Cloud Foundry?

Also:  Have you considered using our https://github.com/pivotal-cf/brokerapi, now that it's open source?

**Comment by ryanmoran** [comment]
I was already planning on moving this.

**Comment by ryanmoran** [comment]
We tried using brokerapi months ago. The experience left a lot to be desired. And then we were told to make our own. So we did. We already have a few projects using envoy. I don't think we are going to switch.

**Comment by goonzoid** [comment]
@ryanmoran I'd be super keen to hear any feedback around troubles you had using brokerapi. There have actually been two incarnations of brokerapi, and while I'll admit that the first one was pretty hard to use (it was never intended for consumption outside of our team) I think the second one should be pretty good.

If you've got time, I'd love an email with any thoughts you have on this. Keen to improve brokerapi where possible.
